### ISSUE TITLE
An error occurs when running a command!

### ISSUE THREAD

**Issue by rexchou** [sonata-project/sandbox#412]
[ReflectionException]
  Class Application\Sonata\ClassificationBundle\Entity\Context does not exist

**Comment by AntonioCS** [comment]
@rande commented on [24 Sep 2014 23:19 BST](https://github.com/sonata-project/sandbox/issues/412#issuecomment-56747897 "2014-09-24T22:19:29Z - Replied by Github Comment Enhancer"):
> The class exist: [https://github.com/sonata-project/sandbox/blob/2.4-develop/src/Application/Sonata/ClassificationBundle/Entity/Context.php](https://github.com/sonata-project/sandbox/blob/2.4-develop/src/Application/Sonata/ClassificationBundle/Entity/Context.php)

If this is fixed in 2.4 why do you still instruct people to get the 2.3 branch in the sonata sanbox page? Your documentation is horrible but I am stuck with this damn thing. I am trying to use the sandbox project to see if I can understand a bit more of this project, you could at least indicate the correct branch to download. A branch were it doesn't error out (what I am experiencing) This was closed on 24 of September you had more than enough time to update the damn readme.

**Comment by krewetka** [comment]
I agree that sonata docs need quite a lot of work to update and to make it easier for newbies who just downloaded it and making first steps.

It took me a lot of time(and a lot of debugging) to make some simple adjustments & changes because of strange errors or information I couldn't find in docs.  At least I now now sonata admin code quite well after all the debugging ;)

Still it's free open source project so I won't complain ...it's still great that someone is working on it to improve it :)

In my case I had to download 2.3 version as 2.4 have main layout of filters rebuilt in a way which is not usable in my project. It's only a pity that I because of that I can't upgrade to 2.4 and some nice changes are made to 2.4 only and not 2.3 anymore.

**Comment by AntonioCS** [comment]
I understand it's free and open source but I assume the user knows it has a lot of people using it. If he doesn't want people to use it  he should put in BIG BOLD letters that the documentation is crap and in many cases wrong has poor examples and that people should not use it.
