### ISSUE TITLE
Try to improve code quality

### ISSUE THREAD

**Issue by paq85** [sonata-project/sandbox#535]
Sension Labs Insight reports a couple of issues:

> Critical security alerts
> Sensitive data should not be present in non-parameter configuration files
> PHP debug statements found

https://insight.sensiolabs.com/projects/161f420d-f0b5-4e4d-9ecd-d13c40f7a77d

It would be nice to fix at least the critical and major ones :)

**Comment by Soullivaneuh** [comment]
@paq85 Feel free to make a PR! ;-)

On https://github.com/sonata-project/sandbox/tree/2.4-develop please if you want to make it.

**Comment by sagikazarmark** [comment]
I checked the issues. Actually most of them is related to some test/debug code. Since this is a sandbox/example, I don't think it is relevant.

It is funny, that Sensio's own code inspecting tool reports .htaccess files as an issue, while symfony itself has a lot of .htacces files in it's standard version.

**Comment by jordisala1991** [comment]
We dont use SensioLabs tool to check code quality. And as @sagikazarmark it is related to test code, so probably not worth fixing.

Closing for now, if you still want to provide a PR to fix it, feel free
