### ISSUE TITLE
page_slug route home

### ISSUE THREAD

**Issue by ferriss** [sonata-project/sandbox#598]
I've setup a few different projects based upon the sandbox now.
Somehow I am not able to override the route to the homepage / 
It keeps being redirected to the page_slug route

I am missing something, but what and where?

**Comment by jordisala1991** [comment]
Please, post this issue on stackOverflow. And if it is really and issue, probably the correct place is the PageBundle, unless the problem relly comes because of the sandbox.

If it is because of the sandbox, please make sure you are using 3.0 branch first, the other ones are too old, and will get removed probably: #610
